// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEzpz-HJUc3QIA_CuDfgBEjnNNhgQ36YA',
    appId: '1:724631896637:android:5713d1fbc6bf61864b2054',
    messagingSenderId: '724631896637',
    projectId: 'dailynutryapp',
    storageBucket: 'dailynutryapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHx5l0BmK06fvwsRqhtxfLdxeTn5t11yk',
    appId: '1:724631896637:ios:292adadb2da9818a4b2054',
    messagingSenderId: '724631896637',
    projectId: 'dailynutryapp',
    storageBucket: 'dailynutryapp.firebasestorage.app',
    iosBundleId: 'com.example.dailynutryapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv4adiu75PetiG5bdFWF3M30VQm_L_HVc',
    appId: '1:724631896637:web:6c5443c59c14147f4b2054',
    messagingSenderId: '724631896637',
    projectId: 'dailynutryapp',
    authDomain: 'dailynutryapp.firebaseapp.com',
    storageBucket: 'dailynutryapp.firebasestorage.app',
    measurementId: 'G-E5N2GMYZ6F',
  );

}